name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    # checks out the repo
    - uses: actions/checkout@v2
    
    # run doxygen
    - uses: mattnotmitt/doxygen-action@1.9.3
      with:
        doxyfile-path: 'docs/Doxyfile'
    
    # deploy
    - uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: master
        folder: .
    
